package com.buding.battle.logic.event;

public enum DeskEventKey {
	PLAYER_READY,
	CHANGE_DESK,
	GAME_MSG,
	PLAYER_AWAY,
	PLAYER_EXIT,
	PLAYER_COMBACK,
	PLAYER_OFFLINE,
	PLAYER_RECONNECT,
	KICKOUT_PLAYER,
	PLAYER_HANGUP,
	PLAYER_CANCELUP,
	DISMISS,
	VOTE_DISSMISS
}
