// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MJBase.proto

package packet.mj;

public final class MJBase {
  private MJBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code packet.mj.GameOperType}
   */
  public enum GameOperType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GameOperStartSyn = 7001;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    GameOperStartSyn(0, 7001),
    /**
     * <code>GameOperHandCardSyn = 7002;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    GameOperHandCardSyn(1, 7002),
    /**
     * <code>GameOperPublicInfoSyn = 7003;</code>
     *
     * <pre>
     *公共信息
     * </pre>
     */
    GameOperPublicInfoSyn(2, 7003),
    /**
     * <code>GameOperPlayerHuSyn = 7004;</code>
     *
     * <pre>
     *公共信息
     * </pre>
     */
    GameOperPlayerHuSyn(3, 7004),
    /**
     * <code>GameOperPlayerActionNotify = 7005;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    GameOperPlayerActionNotify(4, 7005),
    /**
     * <code>GameOperActorSyn = 7006;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    GameOperActorSyn(5, 7006),
    /**
     * <code>GameOperPlayerActionSyn = 7007;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(吃、碰、听、出、吃听、碰听)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    GameOperPlayerActionSyn(6, 7007),
    /**
     * <code>GameOperBaoChangeSyn = 7008;</code>
     *
     * <pre>
     *换宝 
     * </pre>
     */
    GameOperBaoChangeSyn(7, 7008),
    /**
     * <code>GameOperReNofity = 7009;</code>
     *
     * <pre>
     *重新提醒操作,调试用
     * </pre>
     */
    GameOperReNofity(8, 7009),
    /**
     * <code>GameOperFinalSettleSyn = 7010;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    GameOperFinalSettleSyn(9, 7010),
    ;

    /**
     * <code>GameOperStartSyn = 7001;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    public static final int GameOperStartSyn_VALUE = 7001;
    /**
     * <code>GameOperHandCardSyn = 7002;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    public static final int GameOperHandCardSyn_VALUE = 7002;
    /**
     * <code>GameOperPublicInfoSyn = 7003;</code>
     *
     * <pre>
     *公共信息
     * </pre>
     */
    public static final int GameOperPublicInfoSyn_VALUE = 7003;
    /**
     * <code>GameOperPlayerHuSyn = 7004;</code>
     *
     * <pre>
     *公共信息
     * </pre>
     */
    public static final int GameOperPlayerHuSyn_VALUE = 7004;
    /**
     * <code>GameOperPlayerActionNotify = 7005;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    public static final int GameOperPlayerActionNotify_VALUE = 7005;
    /**
     * <code>GameOperActorSyn = 7006;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    public static final int GameOperActorSyn_VALUE = 7006;
    /**
     * <code>GameOperPlayerActionSyn = 7007;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(吃、碰、听、出、吃听、碰听)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    public static final int GameOperPlayerActionSyn_VALUE = 7007;
    /**
     * <code>GameOperBaoChangeSyn = 7008;</code>
     *
     * <pre>
     *换宝 
     * </pre>
     */
    public static final int GameOperBaoChangeSyn_VALUE = 7008;
    /**
     * <code>GameOperReNofity = 7009;</code>
     *
     * <pre>
     *重新提醒操作,调试用
     * </pre>
     */
    public static final int GameOperReNofity_VALUE = 7009;
    /**
     * <code>GameOperFinalSettleSyn = 7010;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    public static final int GameOperFinalSettleSyn_VALUE = 7010;


    public final int getNumber() { return value; }

    public static GameOperType valueOf(int value) {
      switch (value) {
        case 7001: return GameOperStartSyn;
        case 7002: return GameOperHandCardSyn;
        case 7003: return GameOperPublicInfoSyn;
        case 7004: return GameOperPlayerHuSyn;
        case 7005: return GameOperPlayerActionNotify;
        case 7006: return GameOperActorSyn;
        case 7007: return GameOperPlayerActionSyn;
        case 7008: return GameOperBaoChangeSyn;
        case 7009: return GameOperReNofity;
        case 7010: return GameOperFinalSettleSyn;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameOperType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameOperType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameOperType>() {
            public GameOperType findValueByNumber(int number) {
              return GameOperType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return packet.mj.MJBase.getDescriptor().getEnumTypes().get(0);
    }

    private static final GameOperType[] VALUES = values();

    public static GameOperType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GameOperType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:packet.mj.GameOperType)
  }

  public interface GameOperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .packet.mj.GameOperType operType = 1;
    /**
     * <code>required .packet.mj.GameOperType operType = 1;</code>
     *
     * <pre>
     *业务类型
     * </pre>
     */
    boolean hasOperType();
    /**
     * <code>required .packet.mj.GameOperType operType = 1;</code>
     *
     * <pre>
     *业务类型
     * </pre>
     */
    packet.mj.MJBase.GameOperType getOperType();

    // optional bytes content = 2;
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
     * </pre>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code packet.mj.GameOperation}
   */
  public static final class GameOperation extends
      com.google.protobuf.GeneratedMessage
      implements GameOperationOrBuilder {
    // Use GameOperation.newBuilder() to construct.
    private GameOperation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameOperation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameOperation defaultInstance;
    public static GameOperation getDefaultInstance() {
      return defaultInstance;
    }

    public GameOperation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameOperation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              packet.mj.MJBase.GameOperType value = packet.mj.MJBase.GameOperType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                operType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet.mj.MJBase.internal_static_packet_mj_GameOperation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet.mj.MJBase.internal_static_packet_mj_GameOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet.mj.MJBase.GameOperation.class, packet.mj.MJBase.GameOperation.Builder.class);
    }

    public static com.google.protobuf.Parser<GameOperation> PARSER =
        new com.google.protobuf.AbstractParser<GameOperation>() {
      public GameOperation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameOperation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameOperation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .packet.mj.GameOperType operType = 1;
    public static final int OPERTYPE_FIELD_NUMBER = 1;
    private packet.mj.MJBase.GameOperType operType_;
    /**
     * <code>required .packet.mj.GameOperType operType = 1;</code>
     *
     * <pre>
     *业务类型
     * </pre>
     */
    public boolean hasOperType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .packet.mj.GameOperType operType = 1;</code>
     *
     * <pre>
     *业务类型
     * </pre>
     */
    public packet.mj.MJBase.GameOperType getOperType() {
      return operType_;
    }

    // optional bytes content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
     * </pre>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private void initFields() {
      operType_ = packet.mj.MJBase.GameOperType.GameOperStartSyn;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOperType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, operType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static packet.mj.MJBase.GameOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static packet.mj.MJBase.GameOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static packet.mj.MJBase.GameOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(packet.mj.MJBase.GameOperation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet.mj.GameOperation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements packet.mj.MJBase.GameOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.mj.MJBase.internal_static_packet_mj_GameOperation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.mj.MJBase.internal_static_packet_mj_GameOperation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.mj.MJBase.GameOperation.class, packet.mj.MJBase.GameOperation.Builder.class);
      }

      // Construct using packet.mj.MJBase.GameOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        operType_ = packet.mj.MJBase.GameOperType.GameOperStartSyn;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet.mj.MJBase.internal_static_packet_mj_GameOperation_descriptor;
      }

      public packet.mj.MJBase.GameOperation getDefaultInstanceForType() {
        return packet.mj.MJBase.GameOperation.getDefaultInstance();
      }

      public packet.mj.MJBase.GameOperation build() {
        packet.mj.MJBase.GameOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public packet.mj.MJBase.GameOperation buildPartial() {
        packet.mj.MJBase.GameOperation result = new packet.mj.MJBase.GameOperation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operType_ = operType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet.mj.MJBase.GameOperation) {
          return mergeFrom((packet.mj.MJBase.GameOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet.mj.MJBase.GameOperation other) {
        if (other == packet.mj.MJBase.GameOperation.getDefaultInstance()) return this;
        if (other.hasOperType()) {
          setOperType(other.getOperType());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOperType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet.mj.MJBase.GameOperation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet.mj.MJBase.GameOperation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .packet.mj.GameOperType operType = 1;
      private packet.mj.MJBase.GameOperType operType_ = packet.mj.MJBase.GameOperType.GameOperStartSyn;
      /**
       * <code>required .packet.mj.GameOperType operType = 1;</code>
       *
       * <pre>
       *业务类型
       * </pre>
       */
      public boolean hasOperType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .packet.mj.GameOperType operType = 1;</code>
       *
       * <pre>
       *业务类型
       * </pre>
       */
      public packet.mj.MJBase.GameOperType getOperType() {
        return operType_;
      }
      /**
       * <code>required .packet.mj.GameOperType operType = 1;</code>
       *
       * <pre>
       *业务类型
       * </pre>
       */
      public Builder setOperType(packet.mj.MJBase.GameOperType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .packet.mj.GameOperType operType = 1;</code>
       *
       * <pre>
       *业务类型
       * </pre>
       */
      public Builder clearOperType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operType_ = packet.mj.MJBase.GameOperType.GameOperStartSyn;
        onChanged();
        return this;
      }

      // optional bytes content = 2;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
       * </pre>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
       * </pre>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:packet.mj.GameOperation)
    }

    static {
      defaultInstance = new GameOperation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:packet.mj.GameOperation)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_mj_GameOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_packet_mj_GameOperation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014MJBase.proto\022\tpacket.mj\"K\n\rGameOperati" +
      "on\022)\n\010operType\030\001 \002(\0162\027.packet.mj.GameOpe" +
      "rType\022\017\n\007content\030\002 \001(\014*\232\002\n\014GameOperType\022" +
      "\025\n\020GameOperStartSyn\020\3316\022\030\n\023GameOperHandCa" +
      "rdSyn\020\3326\022\032\n\025GameOperPublicInfoSyn\020\3336\022\030\n\023" +
      "GameOperPlayerHuSyn\020\3346\022\037\n\032GameOperPlayer" +
      "ActionNotify\020\3356\022\025\n\020GameOperActorSyn\020\3366\022\034" +
      "\n\027GameOperPlayerActionSyn\020\3376\022\031\n\024GameOper" +
      "BaoChangeSyn\020\3406\022\025\n\020GameOperReNofity\020\3416\022\033" +
      "\n\026GameOperFinalSettleSyn\020\3426"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_packet_mj_GameOperation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_packet_mj_GameOperation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_packet_mj_GameOperation_descriptor,
              new java.lang.String[] { "OperType", "Content", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
