// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rank.proto

package packet.rank;

public final class Rank {
  private Rank() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RankRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code packet.rank.RankRequest}
   */
  public static final class RankRequest extends
      com.google.protobuf.GeneratedMessage
      implements RankRequestOrBuilder {
    // Use RankRequest.newBuilder() to construct.
    private RankRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RankRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RankRequest defaultInstance;
    public static RankRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RankRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RankRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet.rank.Rank.internal_static_packet_rank_RankRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet.rank.Rank.internal_static_packet_rank_RankRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet.rank.Rank.RankRequest.class, packet.rank.Rank.RankRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RankRequest> PARSER =
        new com.google.protobuf.AbstractParser<RankRequest>() {
      public RankRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RankRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RankRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static packet.rank.Rank.RankRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.rank.Rank.RankRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.rank.Rank.RankRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.rank.Rank.RankRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.rank.Rank.RankRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static packet.rank.Rank.RankRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static packet.rank.Rank.RankRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static packet.rank.Rank.RankRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static packet.rank.Rank.RankRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static packet.rank.Rank.RankRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(packet.rank.Rank.RankRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet.rank.RankRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements packet.rank.Rank.RankRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.rank.Rank.internal_static_packet_rank_RankRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.rank.Rank.internal_static_packet_rank_RankRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.rank.Rank.RankRequest.class, packet.rank.Rank.RankRequest.Builder.class);
      }

      // Construct using packet.rank.Rank.RankRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet.rank.Rank.internal_static_packet_rank_RankRequest_descriptor;
      }

      public packet.rank.Rank.RankRequest getDefaultInstanceForType() {
        return packet.rank.Rank.RankRequest.getDefaultInstance();
      }

      public packet.rank.Rank.RankRequest build() {
        packet.rank.Rank.RankRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public packet.rank.Rank.RankRequest buildPartial() {
        packet.rank.Rank.RankRequest result = new packet.rank.Rank.RankRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet.rank.Rank.RankRequest) {
          return mergeFrom((packet.rank.Rank.RankRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet.rank.Rank.RankRequest other) {
        if (other == packet.rank.Rank.RankRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet.rank.Rank.RankRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet.rank.Rank.RankRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:packet.rank.RankRequest)
    }

    static {
      defaultInstance = new RankRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:packet.rank.RankRequest)
  }

  public interface RankSynOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .packet.rank.RankItem coinList = 2;
    /**
     * <code>repeated .packet.rank.RankItem coinList = 2;</code>
     */
    java.util.List<packet.rank.Rank.RankItem> 
        getCoinListList();
    /**
     * <code>repeated .packet.rank.RankItem coinList = 2;</code>
     */
    packet.rank.Rank.RankItem getCoinList(int index);
    /**
     * <code>repeated .packet.rank.RankItem coinList = 2;</code>
     */
    int getCoinListCount();
    /**
     * <code>repeated .packet.rank.RankItem coinList = 2;</code>
     */
    java.util.List<? extends packet.rank.Rank.RankItemOrBuilder> 
        getCoinListOrBuilderList();
    /**
     * <code>repeated .packet.rank.RankItem coinList = 2;</code>
     */
    packet.rank.Rank.RankItemOrBuilder getCoinListOrBuilder(
        int index);

    // repeated .packet.rank.RankItem gameCountList = 1;
    /**
     * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
     */
    java.util.List<packet.rank.Rank.RankItem> 
        getGameCountListList();
    /**
     * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
     */
    packet.rank.Rank.RankItem getGameCountList(int index);
    /**
     * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
     */
    int getGameCountListCount();
    /**
     * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
     */
    java.util.List<? extends packet.rank.Rank.RankItemOrBuilder> 
        getGameCountListOrBuilderList();
    /**
     * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
     */
    packet.rank.Rank.RankItemOrBuilder getGameCountListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code packet.rank.RankSyn}
   */
  public static final class RankSyn extends
      com.google.protobuf.GeneratedMessage
      implements RankSynOrBuilder {
    // Use RankSyn.newBuilder() to construct.
    private RankSyn(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RankSyn(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RankSyn defaultInstance;
    public static RankSyn getDefaultInstance() {
      return defaultInstance;
    }

    public RankSyn getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RankSyn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                gameCountList_ = new java.util.ArrayList<packet.rank.Rank.RankItem>();
                mutable_bitField0_ |= 0x00000002;
              }
              gameCountList_.add(input.readMessage(packet.rank.Rank.RankItem.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                coinList_ = new java.util.ArrayList<packet.rank.Rank.RankItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              coinList_.add(input.readMessage(packet.rank.Rank.RankItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          gameCountList_ = java.util.Collections.unmodifiableList(gameCountList_);
        }
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          coinList_ = java.util.Collections.unmodifiableList(coinList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet.rank.Rank.internal_static_packet_rank_RankSyn_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet.rank.Rank.internal_static_packet_rank_RankSyn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet.rank.Rank.RankSyn.class, packet.rank.Rank.RankSyn.Builder.class);
    }

    public static com.google.protobuf.Parser<RankSyn> PARSER =
        new com.google.protobuf.AbstractParser<RankSyn>() {
      public RankSyn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RankSyn(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RankSyn> getParserForType() {
      return PARSER;
    }

    // repeated .packet.rank.RankItem coinList = 2;
    public static final int COINLIST_FIELD_NUMBER = 2;
    private java.util.List<packet.rank.Rank.RankItem> coinList_;
    /**
     * <code>repeated .packet.rank.RankItem coinList = 2;</code>
     */
    public java.util.List<packet.rank.Rank.RankItem> getCoinListList() {
      return coinList_;
    }
    /**
     * <code>repeated .packet.rank.RankItem coinList = 2;</code>
     */
    public java.util.List<? extends packet.rank.Rank.RankItemOrBuilder> 
        getCoinListOrBuilderList() {
      return coinList_;
    }
    /**
     * <code>repeated .packet.rank.RankItem coinList = 2;</code>
     */
    public int getCoinListCount() {
      return coinList_.size();
    }
    /**
     * <code>repeated .packet.rank.RankItem coinList = 2;</code>
     */
    public packet.rank.Rank.RankItem getCoinList(int index) {
      return coinList_.get(index);
    }
    /**
     * <code>repeated .packet.rank.RankItem coinList = 2;</code>
     */
    public packet.rank.Rank.RankItemOrBuilder getCoinListOrBuilder(
        int index) {
      return coinList_.get(index);
    }

    // repeated .packet.rank.RankItem gameCountList = 1;
    public static final int GAMECOUNTLIST_FIELD_NUMBER = 1;
    private java.util.List<packet.rank.Rank.RankItem> gameCountList_;
    /**
     * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
     */
    public java.util.List<packet.rank.Rank.RankItem> getGameCountListList() {
      return gameCountList_;
    }
    /**
     * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
     */
    public java.util.List<? extends packet.rank.Rank.RankItemOrBuilder> 
        getGameCountListOrBuilderList() {
      return gameCountList_;
    }
    /**
     * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
     */
    public int getGameCountListCount() {
      return gameCountList_.size();
    }
    /**
     * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
     */
    public packet.rank.Rank.RankItem getGameCountList(int index) {
      return gameCountList_.get(index);
    }
    /**
     * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
     */
    public packet.rank.Rank.RankItemOrBuilder getGameCountListOrBuilder(
        int index) {
      return gameCountList_.get(index);
    }

    private void initFields() {
      coinList_ = java.util.Collections.emptyList();
      gameCountList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < gameCountList_.size(); i++) {
        output.writeMessage(1, gameCountList_.get(i));
      }
      for (int i = 0; i < coinList_.size(); i++) {
        output.writeMessage(2, coinList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < gameCountList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gameCountList_.get(i));
      }
      for (int i = 0; i < coinList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, coinList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static packet.rank.Rank.RankSyn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.rank.Rank.RankSyn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.rank.Rank.RankSyn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.rank.Rank.RankSyn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.rank.Rank.RankSyn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static packet.rank.Rank.RankSyn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static packet.rank.Rank.RankSyn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static packet.rank.Rank.RankSyn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static packet.rank.Rank.RankSyn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static packet.rank.Rank.RankSyn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(packet.rank.Rank.RankSyn prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet.rank.RankSyn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements packet.rank.Rank.RankSynOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.rank.Rank.internal_static_packet_rank_RankSyn_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.rank.Rank.internal_static_packet_rank_RankSyn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.rank.Rank.RankSyn.class, packet.rank.Rank.RankSyn.Builder.class);
      }

      // Construct using packet.rank.Rank.RankSyn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCoinListFieldBuilder();
          getGameCountListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (coinListBuilder_ == null) {
          coinList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          coinListBuilder_.clear();
        }
        if (gameCountListBuilder_ == null) {
          gameCountList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          gameCountListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet.rank.Rank.internal_static_packet_rank_RankSyn_descriptor;
      }

      public packet.rank.Rank.RankSyn getDefaultInstanceForType() {
        return packet.rank.Rank.RankSyn.getDefaultInstance();
      }

      public packet.rank.Rank.RankSyn build() {
        packet.rank.Rank.RankSyn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public packet.rank.Rank.RankSyn buildPartial() {
        packet.rank.Rank.RankSyn result = new packet.rank.Rank.RankSyn(this);
        int from_bitField0_ = bitField0_;
        if (coinListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            coinList_ = java.util.Collections.unmodifiableList(coinList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.coinList_ = coinList_;
        } else {
          result.coinList_ = coinListBuilder_.build();
        }
        if (gameCountListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            gameCountList_ = java.util.Collections.unmodifiableList(gameCountList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.gameCountList_ = gameCountList_;
        } else {
          result.gameCountList_ = gameCountListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet.rank.Rank.RankSyn) {
          return mergeFrom((packet.rank.Rank.RankSyn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet.rank.Rank.RankSyn other) {
        if (other == packet.rank.Rank.RankSyn.getDefaultInstance()) return this;
        if (coinListBuilder_ == null) {
          if (!other.coinList_.isEmpty()) {
            if (coinList_.isEmpty()) {
              coinList_ = other.coinList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCoinListIsMutable();
              coinList_.addAll(other.coinList_);
            }
            onChanged();
          }
        } else {
          if (!other.coinList_.isEmpty()) {
            if (coinListBuilder_.isEmpty()) {
              coinListBuilder_.dispose();
              coinListBuilder_ = null;
              coinList_ = other.coinList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              coinListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCoinListFieldBuilder() : null;
            } else {
              coinListBuilder_.addAllMessages(other.coinList_);
            }
          }
        }
        if (gameCountListBuilder_ == null) {
          if (!other.gameCountList_.isEmpty()) {
            if (gameCountList_.isEmpty()) {
              gameCountList_ = other.gameCountList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureGameCountListIsMutable();
              gameCountList_.addAll(other.gameCountList_);
            }
            onChanged();
          }
        } else {
          if (!other.gameCountList_.isEmpty()) {
            if (gameCountListBuilder_.isEmpty()) {
              gameCountListBuilder_.dispose();
              gameCountListBuilder_ = null;
              gameCountList_ = other.gameCountList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              gameCountListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGameCountListFieldBuilder() : null;
            } else {
              gameCountListBuilder_.addAllMessages(other.gameCountList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet.rank.Rank.RankSyn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet.rank.Rank.RankSyn) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .packet.rank.RankItem coinList = 2;
      private java.util.List<packet.rank.Rank.RankItem> coinList_ =
        java.util.Collections.emptyList();
      private void ensureCoinListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          coinList_ = new java.util.ArrayList<packet.rank.Rank.RankItem>(coinList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          packet.rank.Rank.RankItem, packet.rank.Rank.RankItem.Builder, packet.rank.Rank.RankItemOrBuilder> coinListBuilder_;

      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public java.util.List<packet.rank.Rank.RankItem> getCoinListList() {
        if (coinListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(coinList_);
        } else {
          return coinListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public int getCoinListCount() {
        if (coinListBuilder_ == null) {
          return coinList_.size();
        } else {
          return coinListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public packet.rank.Rank.RankItem getCoinList(int index) {
        if (coinListBuilder_ == null) {
          return coinList_.get(index);
        } else {
          return coinListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public Builder setCoinList(
          int index, packet.rank.Rank.RankItem value) {
        if (coinListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoinListIsMutable();
          coinList_.set(index, value);
          onChanged();
        } else {
          coinListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public Builder setCoinList(
          int index, packet.rank.Rank.RankItem.Builder builderForValue) {
        if (coinListBuilder_ == null) {
          ensureCoinListIsMutable();
          coinList_.set(index, builderForValue.build());
          onChanged();
        } else {
          coinListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public Builder addCoinList(packet.rank.Rank.RankItem value) {
        if (coinListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoinListIsMutable();
          coinList_.add(value);
          onChanged();
        } else {
          coinListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public Builder addCoinList(
          int index, packet.rank.Rank.RankItem value) {
        if (coinListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoinListIsMutable();
          coinList_.add(index, value);
          onChanged();
        } else {
          coinListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public Builder addCoinList(
          packet.rank.Rank.RankItem.Builder builderForValue) {
        if (coinListBuilder_ == null) {
          ensureCoinListIsMutable();
          coinList_.add(builderForValue.build());
          onChanged();
        } else {
          coinListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public Builder addCoinList(
          int index, packet.rank.Rank.RankItem.Builder builderForValue) {
        if (coinListBuilder_ == null) {
          ensureCoinListIsMutable();
          coinList_.add(index, builderForValue.build());
          onChanged();
        } else {
          coinListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public Builder addAllCoinList(
          java.lang.Iterable<? extends packet.rank.Rank.RankItem> values) {
        if (coinListBuilder_ == null) {
          ensureCoinListIsMutable();
          super.addAll(values, coinList_);
          onChanged();
        } else {
          coinListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public Builder clearCoinList() {
        if (coinListBuilder_ == null) {
          coinList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          coinListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public Builder removeCoinList(int index) {
        if (coinListBuilder_ == null) {
          ensureCoinListIsMutable();
          coinList_.remove(index);
          onChanged();
        } else {
          coinListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public packet.rank.Rank.RankItem.Builder getCoinListBuilder(
          int index) {
        return getCoinListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public packet.rank.Rank.RankItemOrBuilder getCoinListOrBuilder(
          int index) {
        if (coinListBuilder_ == null) {
          return coinList_.get(index);  } else {
          return coinListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public java.util.List<? extends packet.rank.Rank.RankItemOrBuilder> 
           getCoinListOrBuilderList() {
        if (coinListBuilder_ != null) {
          return coinListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(coinList_);
        }
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public packet.rank.Rank.RankItem.Builder addCoinListBuilder() {
        return getCoinListFieldBuilder().addBuilder(
            packet.rank.Rank.RankItem.getDefaultInstance());
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public packet.rank.Rank.RankItem.Builder addCoinListBuilder(
          int index) {
        return getCoinListFieldBuilder().addBuilder(
            index, packet.rank.Rank.RankItem.getDefaultInstance());
      }
      /**
       * <code>repeated .packet.rank.RankItem coinList = 2;</code>
       */
      public java.util.List<packet.rank.Rank.RankItem.Builder> 
           getCoinListBuilderList() {
        return getCoinListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          packet.rank.Rank.RankItem, packet.rank.Rank.RankItem.Builder, packet.rank.Rank.RankItemOrBuilder> 
          getCoinListFieldBuilder() {
        if (coinListBuilder_ == null) {
          coinListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              packet.rank.Rank.RankItem, packet.rank.Rank.RankItem.Builder, packet.rank.Rank.RankItemOrBuilder>(
                  coinList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          coinList_ = null;
        }
        return coinListBuilder_;
      }

      // repeated .packet.rank.RankItem gameCountList = 1;
      private java.util.List<packet.rank.Rank.RankItem> gameCountList_ =
        java.util.Collections.emptyList();
      private void ensureGameCountListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          gameCountList_ = new java.util.ArrayList<packet.rank.Rank.RankItem>(gameCountList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          packet.rank.Rank.RankItem, packet.rank.Rank.RankItem.Builder, packet.rank.Rank.RankItemOrBuilder> gameCountListBuilder_;

      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public java.util.List<packet.rank.Rank.RankItem> getGameCountListList() {
        if (gameCountListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gameCountList_);
        } else {
          return gameCountListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public int getGameCountListCount() {
        if (gameCountListBuilder_ == null) {
          return gameCountList_.size();
        } else {
          return gameCountListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public packet.rank.Rank.RankItem getGameCountList(int index) {
        if (gameCountListBuilder_ == null) {
          return gameCountList_.get(index);
        } else {
          return gameCountListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public Builder setGameCountList(
          int index, packet.rank.Rank.RankItem value) {
        if (gameCountListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameCountListIsMutable();
          gameCountList_.set(index, value);
          onChanged();
        } else {
          gameCountListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public Builder setGameCountList(
          int index, packet.rank.Rank.RankItem.Builder builderForValue) {
        if (gameCountListBuilder_ == null) {
          ensureGameCountListIsMutable();
          gameCountList_.set(index, builderForValue.build());
          onChanged();
        } else {
          gameCountListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public Builder addGameCountList(packet.rank.Rank.RankItem value) {
        if (gameCountListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameCountListIsMutable();
          gameCountList_.add(value);
          onChanged();
        } else {
          gameCountListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public Builder addGameCountList(
          int index, packet.rank.Rank.RankItem value) {
        if (gameCountListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameCountListIsMutable();
          gameCountList_.add(index, value);
          onChanged();
        } else {
          gameCountListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public Builder addGameCountList(
          packet.rank.Rank.RankItem.Builder builderForValue) {
        if (gameCountListBuilder_ == null) {
          ensureGameCountListIsMutable();
          gameCountList_.add(builderForValue.build());
          onChanged();
        } else {
          gameCountListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public Builder addGameCountList(
          int index, packet.rank.Rank.RankItem.Builder builderForValue) {
        if (gameCountListBuilder_ == null) {
          ensureGameCountListIsMutable();
          gameCountList_.add(index, builderForValue.build());
          onChanged();
        } else {
          gameCountListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public Builder addAllGameCountList(
          java.lang.Iterable<? extends packet.rank.Rank.RankItem> values) {
        if (gameCountListBuilder_ == null) {
          ensureGameCountListIsMutable();
          super.addAll(values, gameCountList_);
          onChanged();
        } else {
          gameCountListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public Builder clearGameCountList() {
        if (gameCountListBuilder_ == null) {
          gameCountList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          gameCountListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public Builder removeGameCountList(int index) {
        if (gameCountListBuilder_ == null) {
          ensureGameCountListIsMutable();
          gameCountList_.remove(index);
          onChanged();
        } else {
          gameCountListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public packet.rank.Rank.RankItem.Builder getGameCountListBuilder(
          int index) {
        return getGameCountListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public packet.rank.Rank.RankItemOrBuilder getGameCountListOrBuilder(
          int index) {
        if (gameCountListBuilder_ == null) {
          return gameCountList_.get(index);  } else {
          return gameCountListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public java.util.List<? extends packet.rank.Rank.RankItemOrBuilder> 
           getGameCountListOrBuilderList() {
        if (gameCountListBuilder_ != null) {
          return gameCountListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gameCountList_);
        }
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public packet.rank.Rank.RankItem.Builder addGameCountListBuilder() {
        return getGameCountListFieldBuilder().addBuilder(
            packet.rank.Rank.RankItem.getDefaultInstance());
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public packet.rank.Rank.RankItem.Builder addGameCountListBuilder(
          int index) {
        return getGameCountListFieldBuilder().addBuilder(
            index, packet.rank.Rank.RankItem.getDefaultInstance());
      }
      /**
       * <code>repeated .packet.rank.RankItem gameCountList = 1;</code>
       */
      public java.util.List<packet.rank.Rank.RankItem.Builder> 
           getGameCountListBuilderList() {
        return getGameCountListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          packet.rank.Rank.RankItem, packet.rank.Rank.RankItem.Builder, packet.rank.Rank.RankItemOrBuilder> 
          getGameCountListFieldBuilder() {
        if (gameCountListBuilder_ == null) {
          gameCountListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              packet.rank.Rank.RankItem, packet.rank.Rank.RankItem.Builder, packet.rank.Rank.RankItemOrBuilder>(
                  gameCountList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          gameCountList_ = null;
        }
        return gameCountListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:packet.rank.RankSyn)
    }

    static {
      defaultInstance = new RankSyn(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:packet.rank.RankSyn)
  }

  public interface RankItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 rank = 1;
    /**
     * <code>optional int32 rank = 1;</code>
     *
     * <pre>
     *排名
     * </pre>
     */
    boolean hasRank();
    /**
     * <code>optional int32 rank = 1;</code>
     *
     * <pre>
     *排名
     * </pre>
     */
    int getRank();

    // optional int32 playerId = 2;
    /**
     * <code>optional int32 playerId = 2;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasPlayerId();
    /**
     * <code>optional int32 playerId = 2;</code>
     *
     * <pre>
     * </pre>
     */
    int getPlayerId();

    // optional string playerName = 3;
    /**
     * <code>optional string playerName = 3;</code>
     */
    boolean hasPlayerName();
    /**
     * <code>optional string playerName = 3;</code>
     */
    java.lang.String getPlayerName();
    /**
     * <code>optional string playerName = 3;</code>
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    // optional string playerHeadImg = 4;
    /**
     * <code>optional string playerHeadImg = 4;</code>
     */
    boolean hasPlayerHeadImg();
    /**
     * <code>optional string playerHeadImg = 4;</code>
     */
    java.lang.String getPlayerHeadImg();
    /**
     * <code>optional string playerHeadImg = 4;</code>
     */
    com.google.protobuf.ByteString
        getPlayerHeadImgBytes();

    // optional int32 point = 5;
    /**
     * <code>optional int32 point = 5;</code>
     */
    boolean hasPoint();
    /**
     * <code>optional int32 point = 5;</code>
     */
    int getPoint();
  }
  /**
   * Protobuf type {@code packet.rank.RankItem}
   */
  public static final class RankItem extends
      com.google.protobuf.GeneratedMessage
      implements RankItemOrBuilder {
    // Use RankItem.newBuilder() to construct.
    private RankItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RankItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RankItem defaultInstance;
    public static RankItem getDefaultInstance() {
      return defaultInstance;
    }

    public RankItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RankItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rank_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              playerId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              playerName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              playerHeadImg_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              point_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet.rank.Rank.internal_static_packet_rank_RankItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet.rank.Rank.internal_static_packet_rank_RankItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet.rank.Rank.RankItem.class, packet.rank.Rank.RankItem.Builder.class);
    }

    public static com.google.protobuf.Parser<RankItem> PARSER =
        new com.google.protobuf.AbstractParser<RankItem>() {
      public RankItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RankItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RankItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 rank = 1;
    public static final int RANK_FIELD_NUMBER = 1;
    private int rank_;
    /**
     * <code>optional int32 rank = 1;</code>
     *
     * <pre>
     *排名
     * </pre>
     */
    public boolean hasRank() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 rank = 1;</code>
     *
     * <pre>
     *排名
     * </pre>
     */
    public int getRank() {
      return rank_;
    }

    // optional int32 playerId = 2;
    public static final int PLAYERID_FIELD_NUMBER = 2;
    private int playerId_;
    /**
     * <code>optional int32 playerId = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 playerId = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public int getPlayerId() {
      return playerId_;
    }

    // optional string playerName = 3;
    public static final int PLAYERNAME_FIELD_NUMBER = 3;
    private java.lang.Object playerName_;
    /**
     * <code>optional string playerName = 3;</code>
     */
    public boolean hasPlayerName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string playerName = 3;</code>
     */
    public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          playerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string playerName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string playerHeadImg = 4;
    public static final int PLAYERHEADIMG_FIELD_NUMBER = 4;
    private java.lang.Object playerHeadImg_;
    /**
     * <code>optional string playerHeadImg = 4;</code>
     */
    public boolean hasPlayerHeadImg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string playerHeadImg = 4;</code>
     */
    public java.lang.String getPlayerHeadImg() {
      java.lang.Object ref = playerHeadImg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          playerHeadImg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string playerHeadImg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerHeadImgBytes() {
      java.lang.Object ref = playerHeadImg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerHeadImg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 point = 5;
    public static final int POINT_FIELD_NUMBER = 5;
    private int point_;
    /**
     * <code>optional int32 point = 5;</code>
     */
    public boolean hasPoint() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 point = 5;</code>
     */
    public int getPoint() {
      return point_;
    }

    private void initFields() {
      rank_ = 0;
      playerId_ = 0;
      playerName_ = "";
      playerHeadImg_ = "";
      point_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rank_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, playerId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPlayerHeadImgBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, point_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rank_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPlayerHeadImgBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, point_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static packet.rank.Rank.RankItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.rank.Rank.RankItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.rank.Rank.RankItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.rank.Rank.RankItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.rank.Rank.RankItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static packet.rank.Rank.RankItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static packet.rank.Rank.RankItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static packet.rank.Rank.RankItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static packet.rank.Rank.RankItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static packet.rank.Rank.RankItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(packet.rank.Rank.RankItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet.rank.RankItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements packet.rank.Rank.RankItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.rank.Rank.internal_static_packet_rank_RankItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.rank.Rank.internal_static_packet_rank_RankItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.rank.Rank.RankItem.class, packet.rank.Rank.RankItem.Builder.class);
      }

      // Construct using packet.rank.Rank.RankItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        playerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        playerHeadImg_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        point_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet.rank.Rank.internal_static_packet_rank_RankItem_descriptor;
      }

      public packet.rank.Rank.RankItem getDefaultInstanceForType() {
        return packet.rank.Rank.RankItem.getDefaultInstance();
      }

      public packet.rank.Rank.RankItem build() {
        packet.rank.Rank.RankItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public packet.rank.Rank.RankItem buildPartial() {
        packet.rank.Rank.RankItem result = new packet.rank.Rank.RankItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rank_ = rank_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.playerName_ = playerName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.playerHeadImg_ = playerHeadImg_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.point_ = point_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet.rank.Rank.RankItem) {
          return mergeFrom((packet.rank.Rank.RankItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet.rank.Rank.RankItem other) {
        if (other == packet.rank.Rank.RankItem.getDefaultInstance()) return this;
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasPlayerName()) {
          bitField0_ |= 0x00000004;
          playerName_ = other.playerName_;
          onChanged();
        }
        if (other.hasPlayerHeadImg()) {
          bitField0_ |= 0x00000008;
          playerHeadImg_ = other.playerHeadImg_;
          onChanged();
        }
        if (other.hasPoint()) {
          setPoint(other.getPoint());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet.rank.Rank.RankItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet.rank.Rank.RankItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 rank = 1;
      private int rank_ ;
      /**
       * <code>optional int32 rank = 1;</code>
       *
       * <pre>
       *排名
       * </pre>
       */
      public boolean hasRank() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 rank = 1;</code>
       *
       * <pre>
       *排名
       * </pre>
       */
      public int getRank() {
        return rank_;
      }
      /**
       * <code>optional int32 rank = 1;</code>
       *
       * <pre>
       *排名
       * </pre>
       */
      public Builder setRank(int value) {
        bitField0_ |= 0x00000001;
        rank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rank = 1;</code>
       *
       * <pre>
       *排名
       * </pre>
       */
      public Builder clearRank() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rank_ = 0;
        onChanged();
        return this;
      }

      // optional int32 playerId = 2;
      private int playerId_ ;
      /**
       * <code>optional int32 playerId = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 playerId = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int32 playerId = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000002;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playerId = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = 0;
        onChanged();
        return this;
      }

      // optional string playerName = 3;
      private java.lang.Object playerName_ = "";
      /**
       * <code>optional string playerName = 3;</code>
       */
      public boolean hasPlayerName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string playerName = 3;</code>
       */
      public java.lang.String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playerName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        java.lang.Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playerName = 3;</code>
       */
      public Builder setPlayerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerName = 3;</code>
       */
      public Builder clearPlayerName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerName = 3;</code>
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        playerName_ = value;
        onChanged();
        return this;
      }

      // optional string playerHeadImg = 4;
      private java.lang.Object playerHeadImg_ = "";
      /**
       * <code>optional string playerHeadImg = 4;</code>
       */
      public boolean hasPlayerHeadImg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string playerHeadImg = 4;</code>
       */
      public java.lang.String getPlayerHeadImg() {
        java.lang.Object ref = playerHeadImg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          playerHeadImg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playerHeadImg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerHeadImgBytes() {
        java.lang.Object ref = playerHeadImg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerHeadImg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playerHeadImg = 4;</code>
       */
      public Builder setPlayerHeadImg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        playerHeadImg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerHeadImg = 4;</code>
       */
      public Builder clearPlayerHeadImg() {
        bitField0_ = (bitField0_ & ~0x00000008);
        playerHeadImg_ = getDefaultInstance().getPlayerHeadImg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerHeadImg = 4;</code>
       */
      public Builder setPlayerHeadImgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        playerHeadImg_ = value;
        onChanged();
        return this;
      }

      // optional int32 point = 5;
      private int point_ ;
      /**
       * <code>optional int32 point = 5;</code>
       */
      public boolean hasPoint() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 point = 5;</code>
       */
      public int getPoint() {
        return point_;
      }
      /**
       * <code>optional int32 point = 5;</code>
       */
      public Builder setPoint(int value) {
        bitField0_ |= 0x00000010;
        point_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 point = 5;</code>
       */
      public Builder clearPoint() {
        bitField0_ = (bitField0_ & ~0x00000010);
        point_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:packet.rank.RankItem)
    }

    static {
      defaultInstance = new RankItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:packet.rank.RankItem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_rank_RankRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_packet_rank_RankRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_rank_RankSyn_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_packet_rank_RankSyn_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_rank_RankItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_packet_rank_RankItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRank.proto\022\013packet.rank\"\r\n\013RankRequest" +
      "\"`\n\007RankSyn\022\'\n\010coinList\030\002 \003(\0132\025.packet.r" +
      "ank.RankItem\022,\n\rgameCountList\030\001 \003(\0132\025.pa" +
      "cket.rank.RankItem\"d\n\010RankItem\022\014\n\004rank\030\001" +
      " \001(\005\022\020\n\010playerId\030\002 \001(\005\022\022\n\nplayerName\030\003 \001" +
      "(\t\022\025\n\rplayerHeadImg\030\004 \001(\t\022\r\n\005point\030\005 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_packet_rank_RankRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_packet_rank_RankRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_packet_rank_RankRequest_descriptor,
              new java.lang.String[] { });
          internal_static_packet_rank_RankSyn_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_packet_rank_RankSyn_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_packet_rank_RankSyn_descriptor,
              new java.lang.String[] { "CoinList", "GameCountList", });
          internal_static_packet_rank_RankItem_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_packet_rank_RankItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_packet_rank_RankItem_descriptor,
              new java.lang.String[] { "Rank", "PlayerId", "PlayerName", "PlayerHeadImg", "Point", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
